mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER '${REPLICATION_USER}'@'${REPLICATION_HOST}' IDENTIFIED BY '${REPLICATION_PASSWORD}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT RELOAD, SUPER, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${REPLICATION_USER}'@'${REPLICATION_HOST}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT EVENT ON ${MYSQL_DATABASE}.* TO '${REPLICATION_USER}'@'${REPLICATION_HOST}';"
