mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER '${REPLICATION_USER}'@'${REPLICATION_HOST}' IDENTIFIED BY '${REPLICATION_PASSWORD}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT SELECT, RELOAD, SUPER, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT, SHOW VIEW ON *.* TO '${REPLICATION_USER}'@'${REPLICATION_HOST}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT EVENT ON ${MYSQL_DATABASE}.* TO '${REPLICATION_USER}'@'${REPLICATION_HOST}';"
