# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'sumolog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
pod 'Alamofire'
pod 'PromiseKit'
pod 'StatusProvider'
pod 'KeychainAccess'
pod 'SwiftyJSON'
pod 'TinyConstraints'
pod 'Eureka'
pod 'ScrollableGraphView'
pod 'PopupDialog'

swift_enforce = [
	'Eureka'
]

post_install do |installer|
	installer.pods_project.targets.each do |target|
  		if swift_enforce.include? target.name
			target.build_configurations.each do |config|
				config.build_settings['SWIFT_ENFORCE_EXCLUSIVE_ACCESS'] = 'off'
			end
		end

	end
end

end
