# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sumolog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Eureka'
  pod 'Alamofire', '~> 4.5'
  pod 'KeychainAccess'

  # Pods for sumolog

end
